### ISSUE TITLE
about normalization

### ISSUE THREAD

**Issue by dzwduan** [jefkine/zeta-learn#1]
will layer norm , group norm be added into it ?i am learning your code,it so perfect lol

**Comment by jefkine** [comment]
Yes sure! that the plan. Will add it soon

**Comment by jefkine** [comment]
LayerNormalization1D added. 
as seen on https://arxiv.org/pdf/1607.06450.pdf, layer norm for GRU and LSTM are set up in the individual time units so this will be added as an option in the GRU Cell and LSTM Cells later on

**Comment by dzwduan** [comment]
great job
